---
name: Gataria CI/CD Dev
on:
  push:
    branches:
      - dev

jobs:
  build-dev:
    name: Build dev
    if: contains (github.ref, 'dev')
    runs-on: self-hosted
    steps:
    - name: Clone repository
      uses: actions/checkout@v3
    - name: Docker login
      run: docker login -u {{ vars.DOCKER_LOGIN }} -p {{ secrets.DOCKER_PASS }}
    - name: Docker build
      run: docker build -t fernandindtjr/gataria-frontend:dev$GITHUB_SHA . --build-arg REACT_APP_STAGE:dev
    - name: docker push
      run: docker push fernandindtjr/gataria-frontend:dev$GITHUB_SHA
  test-dev:
    name: Test dev
    if: contains (github.ref, 'dev')
    runs-on: self-hosted
    needs: build-dev
    steps:
    - name: Step 1
      run: env
  deploy-dev:
    name: Deploy dev
    if: contains (github.ref, 'dev')
    runs-on: self-hosted
    needs: test-dev
    container: 
      image: fernandindtjr/gataria-deploy:1.0
      credentials: 
        username:
        password: 

    steps:
<<<<<<< main
    - name: run command
      run: echo $GITHUB_SHA
=======
    - name: Add ChartMuseum Repo
      run: helm repo add gataria-charts http://chartmuseum:8080   
    - name: helm update repo
      run: helm repo update
    - name: Deploy dev
      run: helm upgrade gataria-frontend gataria-charts/gataria-frontend -n dev --set "image.tag=dev$GITHUB_SHA" --set "ingress.hosts[0].hosts=dev.gataria.example" --set "ingress.hosts[0].paths[0].path=/*" --set "ingress.hosts[0].paths[0].pathType=Prefix" || helm install gataria-frontend gataria-charts/gataria-frontend -n dev --set "image.tag=dev$GITHUB_SHA" --set "ingress.hosts[0].hosts=dev.gataria.example" --set "ingress.hosts[0].paths[0].path=/*" --set "ingress.hosts[0].paths[0].pathType=Prefix"
>>>>>>> local
